# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20180702_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='newfield',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='product',
            name='newnew_field',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
