# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 19:43
from __future__ import unicode_literals

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20180630_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=oscar.models.fields.NullCharField(help_text='TEST TEST TEST TEST TEST a product which is not specific to a particular  supplier. Eg an ISBN for a book.', max_length=64, unique=True, verbose_name='EAN'),
        ),
    ]
