# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0018_auto_20180702_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='subsubcategory',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
