# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0019_auto_20180702_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
