# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20180705_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='entity_object_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_file',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_float',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_image',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_integer',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_richtext',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
