# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_remove_productattributevalue_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='test',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
